pk <- c("AdvancedBasketballStats",
        "aRbs",
        "baseballDBR",
        "BasketballAnalyzeR",
        "BAwiR",
        "bigchess",
        "BradleyTerry2",
        "cfbfastR",
        "chess",
        "chessR",
        "colorr",
        "combinedevents",
        "cricketdata",
        "cricketr",
        "engsoccerdata",
        "fastRhockey",
        "fbRanks",
        "fflr",
        "ffscrapr",
        "ffsimulator",
        "fitzRoy",
        "footballpenaltiesBL",
        "footBayes",
        "ggsoccer",
        "gsisdecoder",
        "hockeyR",
        "hoopR",
        "implied",
        "itscalledsoccer",
        "JumpeR",
        "Lahman",
        "mlbstats",
        "mlbstatsR",
        "mvglmmRank",
        "NBAloveR",
        "nbapalettes",
        "nfl4th",
        "nflfastR",
        "nflreadr",
        "nflseedR",
        "nhlapi",
        "NHLData",
        "nhlscrape",
        "odds.converter",
        "pinnacle.data",
        "piratings",
        "pitchRx",
        "qqr",
        "rchess",
        "RDota2",
        "retrosheet",
        "RKelly",
        "rStrava",
        "runexp",
        "socceR",
        "SpatialBall",
        "SportsAnalytics",
        "SportsTour",
        "sportyR",
        "stockfish",
        "SwimmeR",
        "teamcolors",
        "TouRnament",
        "trackeR",
        "trackeRapp",
        "uncmbb",
        "volleystat",
        "wehoop",
        "worldfootballR",
        "yorkr")

library(packageRank)
pk_downloads <- pk %>% 
  cranDownloads(to = Sys.Date())

pk_downloads %>% 
  pluck("cranlogs.data") %>% 
  group_by(package) %>% 
  slice_max(cumulative) %>% 
  arrange(desc(cumulative)) 
